### ISSUE TITLE
Use non-blocking request-controller

### ISSUE THREAD

**Issue by doxsch** [yb-hackathon-code-butcher/codebase#77] opened 2020-10-12 19:02 UTC
btw. for you devs: this is how you create reactive (non-blocking) request-controllers. because we have netty and webflux (so basically, because we can 😄)

_Originally posted by @bbortt in https://github.com/yb-hackathon-code-butcher/codebase/pull/67#discussion_r503087404_

**Comment by bbortt** [comment] 2020-10-12 19:50
actually, a duplicate of #69 .

**Closed as completed by bbortt** 2020-10-12 19:50 UTC
